// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#include "rtap_db_dict-pimpl.hxx"
#include "rtap_db_dict.hxx"

#include <iostream>

// 
// NB Допустимый диапазон всех параметров задан в rtap_db_dict.xsd
//
namespace rtap_db_dict
{
  // ObjClassEntry_pimpl
  //

  void ObjClassEntry_pimpl::
  pre ()
  {
  }

  // [ TS(0)..HIST(80) ]
  rtap_db_dict::ObjClass_t ObjClassEntry_pimpl::
  post_ObjClassEntry ()
  {
    long long v (post_integer ());
    rtap_db_dict::ObjClass_t objclass = UNUSED;

    if ((TS <= v) && (v <= HIST))
      objclass = static_cast<rtap_db_dict::ObjClass_t>(v);
    
    return objclass;
  }

  // ValueEntry_pimpl
  //

  void ValueEntry_pimpl::
  pre ()
  {
  }

  rtap_db_dict::id_t ValueEntry_pimpl::
  post_ValueEntry ()
  {
    long long v (post_integer ());

    // TODO
    //
    // return ... ;
  }

  // ValueLabelEntry_pimpl
  //

  void ValueLabelEntry_pimpl::
  pre ()
  {
  }

  rtap_db_dict::Label_t& ValueLabelEntry_pimpl::
  post_ValueLabelEntry ()
  {
    const ::std::string& v (post_string ());

    // TODO
    //
    // return ... ;
  }

  // UnityIdEntry_pimpl
  //

  void UnityIdEntry_pimpl::
  pre ()
  {
  }

  rtap_db_dict::id_t UnityIdEntry_pimpl::
  post_UnityIdEntry ()
  {
    long long v (post_integer ());

    // TODO
    //
    // return ... ;
  }

  // UnityDimensionType_pimpl
  //

  void UnityDimensionType_pimpl::
  pre ()
  {
  }

  rtap_db_dict::id_t UnityDimensionType_pimpl::
  post_UnityDimensionType ()
  {
    long long v (post_integer ());

    // TODO
    //
    // return ... ;
  }

  // UnityDimensionEntry_pimpl
  //

  void UnityDimensionEntry_pimpl::
  pre ()
  {
  }

  rtap_db_dict::Label_t& UnityDimensionEntry_pimpl::
  post_UnityDimensionEntry ()
  {
    const ::std::string& v (post_string ());

    // TODO
    //
    // return ... ;
  }

  // UnityIdType_pimpl
  //

  void UnityIdType_pimpl::
  pre ()
  {
  }

  rtap_db_dict::id_t UnityIdType_pimpl::
  post_UnityIdType ()
  {
    long long v (post_integer ());

    // TODO
    //
    // return ... ;
  }

  // UnityLabelEntry_pimpl
  //

  void UnityLabelEntry_pimpl::
  pre ()
  {
  }

  rtap_db_dict::Label_t& UnityLabelEntry_pimpl::
  post_UnityLabelEntry ()
  {
    const ::std::string& v (post_string ());

    // TODO
    //
    // return ... ;
  }

  // UnityDesignationEntry_pimpl
  //

  void UnityDesignationEntry_pimpl::
  pre ()
  {
  }

  rtap_db_dict::Label_t& UnityDesignationEntry_pimpl::
  post_UnityDesignationEntry ()
  {
    const ::std::string& v (post_string ());

    // TODO
    //
    // return ... ;
  }

  // InfoTypeEntry_pimpl
  //

  void InfoTypeEntry_pimpl::
  pre ()
  {
  }

  rtap_db_dict::Label_t& InfoTypeEntry_pimpl::
  post_InfoTypeEntry ()
  {
    const ::std::string& v (post_string ());

    // TODO
    //
    // return ... ;
  }

  // Dictionaries_pimpl
  //

  void Dictionaries_pimpl::
  pre ()
  {
  }

  void Dictionaries_pimpl::
  UNITY_LABEL ()
  {
  }

  void Dictionaries_pimpl::
  VAL_LABEL ()
  {
  }

  void Dictionaries_pimpl::
  INFO_TYPES ()
  {
  }

  void Dictionaries_pimpl::
  post_Dictionaries ()
  {
  }

  // UNITY_LABEL_pimpl
  //

  void UNITY_LABEL_pimpl::
  pre ()
  {
  }

  void UNITY_LABEL_pimpl::
  UnityDimensionId (const rtap_db_dict::id_t& UnityDimensionId)
  {
    // TODO
    //
  }

  void UNITY_LABEL_pimpl::
  UnityDimension (rtap_db_dict::Label_t& UnityDimension)
  {
    // TODO
    //
  }

  void UNITY_LABEL_pimpl::
  UnityId (const rtap_db_dict::id_t& UnityId)
  {
    // TODO
    //
  }

  void UNITY_LABEL_pimpl::
  UnityLabel (rtap_db_dict::Label_t& UnityLabel)
  {
    // TODO
    //
  }

  void UNITY_LABEL_pimpl::
  UnityDesignation (rtap_db_dict::Label_t& UnityDesignation)
  {
    // TODO
    //
  }

  void UNITY_LABEL_pimpl::
  post_UNITY_LABEL ()
  {
  }

  // VAL_LABEL_pimpl
  //

  void VAL_LABEL_pimpl::
  pre ()
  {
  }

  void VAL_LABEL_pimpl::
  ObjClass (const rtap_db_dict::ObjClass_t& ObjClass)
  {
    // TODO
    //
  }

  void VAL_LABEL_pimpl::
  Val (const rtap_db_dict::id_t& Val)
  {
    // TODO
    //
  }

  void VAL_LABEL_pimpl::
  ValueLabel (rtap_db_dict::Label_t& ValueLabel)
  {
    // TODO
    //
  }

  void VAL_LABEL_pimpl::
  post_VAL_LABEL ()
  {
  }

  // INFO_TYPES_pimpl
  //

  void INFO_TYPES_pimpl::
  pre ()
  {
  }

  void INFO_TYPES_pimpl::
  ObjClass (const rtap_db_dict::ObjClass_t& ObjClass)
  {
    // TODO
    //
  }

  void INFO_TYPES_pimpl::
  IntoType (rtap_db_dict::Label_t& IntoType)
  {
    // TODO
    //
  }

  void INFO_TYPES_pimpl::
  InfoTypeDesignation (const ::std::string& InfoTypeDesignation)
  {
    std::cout << "InfoTypeDesignation: " << InfoTypeDesignation << std::endl;
  }

  void INFO_TYPES_pimpl::
  post_INFO_TYPES ()
  {
  }
}

