// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

#ifndef PROTOBUF_common_2eproto__INCLUDED
#define PROTOBUF_common_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_common_2eproto();
void protobuf_AssignDesc_common_2eproto();
void protobuf_ShutdownFile_common_2eproto();

class CommonRequest;

// ===================================================================

class CommonRequest : public ::google::protobuf::Message {
 public:
  CommonRequest();
  virtual ~CommonRequest();
  
  CommonRequest(const CommonRequest& from);
  
  inline CommonRequest& operator=(const CommonRequest& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const CommonRequest& default_instance();
  
  void Swap(CommonRequest* other);
  
  // implements Message ----------------------------------------------
  
  CommonRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CommonRequest& from);
  void MergeFrom(const CommonRequest& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 field_1_int32 = 1;
  inline bool has_field_1_int32() const;
  inline void clear_field_1_int32();
  static const int kField1Int32FieldNumber = 1;
  inline ::google::protobuf::int32 field_1_int32() const;
  inline void set_field_1_int32(::google::protobuf::int32 value);
  
  // required string field_2_string = 2;
  inline bool has_field_2_string() const;
  inline void clear_field_2_string();
  static const int kField2StringFieldNumber = 2;
  inline const ::std::string& field_2_string() const;
  inline void set_field_2_string(const ::std::string& value);
  inline void set_field_2_string(const char* value);
  inline void set_field_2_string(const char* value, size_t size);
  inline ::std::string* mutable_field_2_string();
  inline ::std::string* release_field_2_string();
  
  // required int32 field_3_int32 = 3;
  inline bool has_field_3_int32() const;
  inline void clear_field_3_int32();
  static const int kField3Int32FieldNumber = 3;
  inline ::google::protobuf::int32 field_3_int32() const;
  inline void set_field_3_int32(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:CommonRequest)
 private:
  inline void set_has_field_1_int32();
  inline void clear_has_field_1_int32();
  inline void set_has_field_2_string();
  inline void clear_has_field_2_string();
  inline void set_has_field_3_int32();
  inline void clear_has_field_3_int32();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* field_2_string_;
  ::google::protobuf::int32 field_1_int32_;
  ::google::protobuf::int32 field_3_int32_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_common_2eproto();
  friend void protobuf_AssignDesc_common_2eproto();
  friend void protobuf_ShutdownFile_common_2eproto();
  
  void InitAsDefaultInstance();
  static CommonRequest* default_instance_;
};
// ===================================================================


// ===================================================================

// CommonRequest

// required int32 field_1_int32 = 1;
inline bool CommonRequest::has_field_1_int32() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CommonRequest::set_has_field_1_int32() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CommonRequest::clear_has_field_1_int32() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CommonRequest::clear_field_1_int32() {
  field_1_int32_ = 0;
  clear_has_field_1_int32();
}
inline ::google::protobuf::int32 CommonRequest::field_1_int32() const {
  return field_1_int32_;
}
inline void CommonRequest::set_field_1_int32(::google::protobuf::int32 value) {
  set_has_field_1_int32();
  field_1_int32_ = value;
}

// required string field_2_string = 2;
inline bool CommonRequest::has_field_2_string() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CommonRequest::set_has_field_2_string() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CommonRequest::clear_has_field_2_string() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CommonRequest::clear_field_2_string() {
  if (field_2_string_ != &::google::protobuf::internal::kEmptyString) {
    field_2_string_->clear();
  }
  clear_has_field_2_string();
}
inline const ::std::string& CommonRequest::field_2_string() const {
  return *field_2_string_;
}
inline void CommonRequest::set_field_2_string(const ::std::string& value) {
  set_has_field_2_string();
  if (field_2_string_ == &::google::protobuf::internal::kEmptyString) {
    field_2_string_ = new ::std::string;
  }
  field_2_string_->assign(value);
}
inline void CommonRequest::set_field_2_string(const char* value) {
  set_has_field_2_string();
  if (field_2_string_ == &::google::protobuf::internal::kEmptyString) {
    field_2_string_ = new ::std::string;
  }
  field_2_string_->assign(value);
}
inline void CommonRequest::set_field_2_string(const char* value, size_t size) {
  set_has_field_2_string();
  if (field_2_string_ == &::google::protobuf::internal::kEmptyString) {
    field_2_string_ = new ::std::string;
  }
  field_2_string_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* CommonRequest::mutable_field_2_string() {
  set_has_field_2_string();
  if (field_2_string_ == &::google::protobuf::internal::kEmptyString) {
    field_2_string_ = new ::std::string;
  }
  return field_2_string_;
}
inline ::std::string* CommonRequest::release_field_2_string() {
  clear_has_field_2_string();
  if (field_2_string_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = field_2_string_;
    field_2_string_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// required int32 field_3_int32 = 3;
inline bool CommonRequest::has_field_3_int32() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CommonRequest::set_has_field_3_int32() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CommonRequest::clear_has_field_3_int32() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CommonRequest::clear_field_3_int32() {
  field_3_int32_ = 0;
  clear_has_field_3_int32();
}
inline ::google::protobuf::int32 CommonRequest::field_3_int32() const {
  return field_3_int32_;
}
inline void CommonRequest::set_field_3_int32(::google::protobuf::int32 value) {
  set_has_field_3_int32();
  field_3_int32_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_common_2eproto__INCLUDED
