# - Try to find the PROTOBUF library
# Once done this will define
#
#  LIBPROTOBUF_FOUND - system has PROTOBUF
#  LIBPROTOBUF_INCLUDES - the PROTOBUF include directories
#  LIBPROTOBUF_LIBRARIES - The libraries needed to use PROTOBUF

SET (LIBPROTOBUF_VERSION "2.5.0")
#SET (LIBPROTOBUF_INCLUDE_DIR "${RTDBUS_SOURCE_DIR}/../../protobuf-${LIBPROTOBUF_VERSION}/src")
SET (LIBPROTOBUF_INCLUDE_DIR "${RTDBUS_SOURCE_DIR}/../../protobuf/src")
#SET (LIBPROTOBUF_LIBRARIES_DIR "${RTDBUS_SOURCE_DIR}/../../protobuf-${LIBPROTOBUF_VERSION}/src/.libs")
SET (LIBPROTOBUF_LIBRARIES_DIR "${RTDBUS_SOURCE_DIR}/../../protobuf/src/.libs")
SET (PROTOC "${LIBPROTOBUF_LIBRARIES_DIR}/protoc")
#SET (ENV{LD_LIBRARY_PATH} "$ENV{LD_LIBRARY_PATH}:${LIBPROTOBUF_LIBRARIES_DIR}")
#SET (PROTOC_STUB "LD_LIBRARY_PATH=${LIBPROTOBUF_LIBRARIES_DIR} ${PROTOC}")
SET (LIBPROTOBUF_LIBRARIES "protobuf")
SET (LIBPROTOBUF_FOUND TRUE)
