# - Try to find the EXTREMEDB library
# Once done this will define
#
#  LIBEXTREMEDB_FOUND - system has GLIB
#  LIBEXTREMEDB_INCLUDE_DIR - the EXTREMEDB include directories
#  LIBEXTREMEDB_LIBRARIES - The libraries needed to use EXTREMEDB

if (LIBEXTREMEDB_INCLUDE_DIR AND LIBEXTREMEDB_LIBRARIES)

    # in cache already
    SET(LIBEXTREMEDB_FOUND TRUE)

else (LIBEXTREMEDB_INCLUDE_DIR AND LIBEXTREMEDB_LIBRARIES)

  SET (LIBEXTREMEDB_INCLUDE_DIR "${RTDBUS_SOURCE_DIR}/../../master_eXtremeDB_3.5.987_sunos/sources/include")
  SET (LIBEXTREMEDB_LIBRARIES_DIR "${RTDBUS_SOURCE_DIR}/../../master_eXtremeDB_3.5.987_sunos/sources/target/bin.so")
  SET (LIBEXTREMEDB_LIBRARIES "mcossun mcounrt mcovtmem mcouwrt")
  SET (LIBEXTREMEDB_FOUND TRUE)
  MARK_AS_ADVANCED(LIBEXTREMEDB_INCLUDE_DIR LIBEXTREMEDB_LIBRARIES_DIR LIBEXTREMEDB_LIBRARIES)

endif (LIBEXTREMEDB_INCLUDE_DIR AND LIBEXTREMEDB_LIBRARIES)
