# - Try to find the PROTOBUF library
# Once done this will define
#
#  LIBPROTOBUF_FOUND - system has PROTOBUF
#  LIBPROTOBUF_INCLUDES - the PROTOBUF include directories
#  LIBPROTOBUF_LIBRARIES - The libraries needed to use PROTOBUF

if (LIBPROTOBUF_INCLUDE_DIR AND LIBPROTOBUF_LIBRARIES)

    # in cache already
    SET(LIBPROTOBUF_FOUND TRUE)

else (LIBPROTOBUF_INCLUDE_DIR AND LIBPROTOBUF_LIBRARIES)

  SET (LIBPROTOBUF_INCLUDE_DIR "${RTDBUS_SOURCE_DIR}/../../protobuf-2.4.1/src/google/protobuf")
  SET (LIBPROTOBUF_LIBRARIES_DIR "${RTDBUS_SOURCE_DIR}/../../protobuf-2.4.1/src/.libs")
  SET (LIBPROTOBUF_LIBRARIES "protobuf")
  SET (LIBPROTOBUF_FOUND TRUE)
  MARK_AS_ADVANCED(LIBPROTOBUF_INCLUDE_DIR LIBPROTOBUF_LIBRARIES_DIR LIBPROTOBUF_LIBRARIES)

endif (LIBPROTOBUF_INCLUDE_DIR AND LIBPROTOBUF_LIBRARIES)
