// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#include "rtap_db-pimpl.hxx"

namespace rtap_db
{
  // ClassType_pimpl
  //

  void ClassType_pimpl::
  pre ()
  {
  }

  void ClassType_pimpl::
  post_ClassType ()
  {
    const ::std::string& v (post_string ());

    // TODO
    //
  }

  // AttributeType_pimpl
  //

  void AttributeType_pimpl::
  pre ()
  {
  }

  void AttributeType_pimpl::
  post_AttributeType ()
  {
    const ::std::string& v (post_string ());

    // TODO
    //
  }

  // PointKind_pimpl
  //

  void PointKind_pimpl::
  pre ()
  {
  }

  void PointKind_pimpl::
  post_PointKind ()
  {
    const ::std::string& v (post_string ());

    // TODO
    //
  }

  // Class_pimpl
  //

  void Class_pimpl::
  pre ()
  {
  }

  void Class_pimpl::
  Code ()
  {
  }

  void Class_pimpl::
  Name ()
  {
  }

  void Class_pimpl::
  Attr ()
  {
  }

  void Class_pimpl::
  post_Class ()
  {
  }

  // Code_pimpl
  //

  void Code_pimpl::
  pre ()
  {
  }

  void Code_pimpl::
  post_Code ()
  {
    long long v (post_integer ());

    // TODO
    //
  }

  // Attr_pimpl
  //

  void Attr_pimpl::
  pre ()
  {
  }

  void Attr_pimpl::
  Kind ()
  {
  }

  void Attr_pimpl::
  Accessibility ()
  {
  }

  void Attr_pimpl::
  DeType ()
  {
  }

  void Attr_pimpl::
  post_Attr ()
  {
  }

  // Accessibility_pimpl
  //

  void Accessibility_pimpl::
  pre ()
  {
  }

  void Accessibility_pimpl::
  post_Accessibility ()
  {
    const ::std::string& v (post_string ());

    // TODO
    //
  }
}

