// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#ifndef RTAP_DB_PIMPL_HXX
#define RTAP_DB_PIMPL_HXX

#include "rtap_db.hxx"
#include "rtap_db-pskel.hxx"

namespace rtap_db
{
  class ClassType_pimpl: public virtual ClassType_pskel,
    public ::xml_schema::string_pimpl
  {
    public:
    virtual void
    pre ();

    virtual void
    post_ClassType ();
  };

  class AttributeType_pimpl: public virtual AttributeType_pskel,
    public ::xml_schema::string_pimpl
  {
    public:
    virtual void
    pre ();

    virtual void
    post_AttributeType ();
  };

  class PointKind_pimpl: public virtual PointKind_pskel,
    public ::xml_schema::string_pimpl
  {
    public:
    virtual void
    pre ();

    virtual void
    post_PointKind ();
  };

  class Class_pimpl: public virtual Class_pskel
  {
    public:
    virtual void
    pre ();

    virtual void
    Code ();

    virtual void
    Name ();

    virtual void
    Attr ();

    virtual void
    post_Class ();
  };

  class Code_pimpl: public virtual Code_pskel,
    public ::xml_schema::integer_pimpl
  {
    public:
    virtual void
    pre ();

    virtual void
    post_Code ();
  };

  class Attr_pimpl: public virtual Attr_pskel
  {
    public:
    virtual void
    pre ();

    virtual void
    Kind ();

    virtual void
    Accessibility ();

    virtual void
    DeType ();

    virtual void
    post_Attr ();
  };

  class Accessibility_pimpl: public virtual Accessibility_pskel,
    public ::xml_schema::string_pimpl
  {
    public:
    virtual void
    pre ();

    virtual void
    post_Accessibility ();
  };
}

#endif // RTAP_DB_PIMPL_HXX
